[window]
padding = { x = 5, y = 5 }
decorations = "none"
opacity = 0.8


[font]
size = 12
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMonoNL Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMonoNL Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMonoNL Nerd Font", style = "BoldItalic" }


[colors.primary]
background = "#000000"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#cdd6f4"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[colors.dim]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"


# Colors (Kanagawa Dragon)
# Source https//github.com/rebelot/kanagawa.nvim

# [colors.primary]
# # background = "#181616"
# background = "#000000"
# foreground = "#c5c9c5"
#
# [colors.normal]
# black = "#0d0c0c"
# blue = "#8ba4b0"
# cyan = "#8ea4a2"
# green = "#8a9a7b"
# magenta = "#a292a3"
# red = "#c4746e"
# white = "#C8C093"
# yellow = "#c4b28a"
#
# [colors.bright]
# black = "#a6a69c"
# blue = "#7FB4CA"
# cyan = "#7AA89F"
# green = "#87a987"
# magenta = "#938AA9"
# red = "#E46876"
# white = "#c5c9c5"
# yellow = "#E6C384"
#
# [colors.selection]
# background = "#2d4f67"
# foreground = "#c8c093"
#
# [[colors.indexed_colors]]
# index = 16
# color = "#ffa066"
#
# [[colors.indexed_colors]]
# index = 17
# color = "#ff5d62"

